use Crystal;
DELETE FROM DielDissLanguage WHERE ID NOT IN (SELECT MIN(ID) FROM DielDissLanguage GROUP BY HeadClue, SingCode, FreqDiss, Temper_3, TangName, TangentD, ErrDiss, Bknumber, __MethodY, LanguageID);
DELETE FROM ElOpTablLanguage WHERE ID NOT IN (SELECT MIN(ID) FROM ElOpTablLanguage GROUP BY HeadClue, SingCode, WvLeng, ZnN1, R, ErrR, Bknumber, __MethodR, LanguageID);
DELETE FROM EsOpTablLanguage WHERE ID NOT IN (SELECT MIN(ID) FROM EsOpTablLanguage GROUP BY HeadClue, SingCode, LengWave, ZnP, P, ErrP, Bknumber, __MethodP, LanguageID);
DELETE FROM ElemTablNewLanguage WHERE ID NOT IN (SELECT MIN(ID) FROM ElemTablNewLanguage GROUP BY HeadClue, SingCode, A, AErr, B, BErr, C, CErr, Alpha, AlphaErr, Beta, BetaErr, Gamma, GammaErr, Bknumber, __MethodP, LanguageID);
DELETE FROM MechTablLanguage WHERE ID NOT IN (SELECT MIN(ID) FROM MechTablLanguage GROUP BY HeadClue, SingCode, Bknumber, FreqCons, Temper, ZnK, K, ErrK, __MethodK, LanguageID);
DELETE FROM NlOpTablLanguage WHERE ID NOT IN (SELECT MIN(ID) FROM NlOpTablLanguage GROUP BY HeadClue, SingCode, Lyambda, ZnR, Rij, ErrRij, Bknumber, __MethodR, LanguageID);
DELETE FROM LastModifiedLanguage WHERE ID NOT IN (SELECT MIN(ID) FROM LastModifiedLanguage GROUP BY Text, LastModified, LanguageID);
DELETE FROM GrafTablLanguage WHERE ID NOT IN (SELECT MIN(ID) FROM GrafTablLanguage GROUP BY HeadClue, NompClue, NameGraf, Signatur, LanguageID);
DELETE FROM PlavTablLanguage WHERE ID NOT IN (SELECT MIN(ID) FROM PlavTablLanguage GROUP BY HeadClue, PlavType, PlavTemp, ErrPlav, Bknumber, LanguageID);
DELETE FROM Elastic1Language WHERE ID NOT IN (SELECT MIN(ID) FROM Elastic1Language GROUP BY Elastic1ID, LanguageID, ZnE, __MethodE);
DELETE FROM MnOpTablLanguage WHERE ID NOT IN (SELECT MIN(ID) FROM MnOpTablLanguage GROUP BY MnOpTablID, LanguageID, __MethodK);
DELETE FROM CuryTablLanguage WHERE ID NOT IN (SELECT MIN(ID) FROM CuryTablLanguage GROUP BY HeadClue, CuryTemp, ErrCury, Oboztran, Bknumber, LanguageID);
DELETE FROM ModfTablLanguage WHERE ID NOT IN (SELECT MIN(ID) FROM ModfTablLanguage GROUP BY ModfTablID, LanguageID, SpaceGrp);
DELETE FROM HardTablLanguage WHERE ID NOT IN (SELECT MIN(ID) FROM HardTablLanguage GROUP BY HeadClue, SingCode, Hard1, Hard2, ErrHard, Mohs, ErrMohs, Bknumber, __MethodH, LanguageID);
DELETE FROM SuspTablLanguage WHERE ID NOT IN (SELECT MIN(ID) FROM SuspTablLanguage GROUP BY HeadClue, Temper, SuspName, Suspense, ErrSusp, Bknumber, __MethodS, LanguageID);
DELETE FROM PzElTablLanguage WHERE ID NOT IN (SELECT MIN(ID) FROM PzElTablLanguage GROUP BY PzElTablID, LanguageID, __MethodPz);
DELETE FROM RefrcIndLanguage WHERE ID NOT IN (SELECT MIN(ID) FROM RefrcIndLanguage GROUP BY RefrcIndID, LanguageID, __MethodIn);
DELETE FROM DecrTablLanguage WHERE ID NOT IN (SELECT MIN(ID) FROM DecrTablLanguage GROUP BY HeadClue, SingCode, Nzv, Uzv, WaveType, WaveSpeed, Decrement, DecrFreq, Bknumber, LanguageID);
DELETE FROM DielectrLanguage WHERE ID NOT IN (SELECT MIN(ID) FROM DielectrLanguage GROUP BY DielectrID, LanguageID, Znak, __MethodY);
DELETE FROM HeatExpnLanguage WHERE ID NOT IN (SELECT MIN(ID) FROM HeatExpnLanguage GROUP BY HeadClue, SingCode, DataType, Temper_1, Temper_2, Znak1, S11, ErrHExp, Bknumber, __MethodEx, LanguageID);
DELETE FROM ElemTablLanguage WHERE ID NOT IN (SELECT MIN(ID) FROM ElemTablLanguage GROUP BY ElemTablID, LanguageID, __MethodP);
DELETE FROM PropertiesLanguage WHERE ID NOT IN (SELECT MIN(ID) FROM PropertiesLanguage GROUP BY PropertiesID, LanguageID, NAZVPROP);
DELETE FROM HeatTablLanguage WHERE ID NOT IN (SELECT MIN(ID) FROM HeatTablLanguage GROUP BY HeatTablID, LanguageID, __MethodC);
DELETE FROM DensTablLanguage WHERE ID NOT IN (SELECT MIN(ID) FROM DensTablLanguage GROUP BY HeadClue, SingCode, Density, ErrDens, Bknumber, __MethodD, LanguageID);
DELETE FROM AcOpTablLanguage WHERE ID NOT IN (SELECT MIN(ID) FROM AcOpTablLanguage GROUP BY AcOpTablID, LanguageID, E, Nsv, Uzv);
DELETE FROM BibliogrLanguage WHERE ID NOT IN (SELECT MIN(ID) FROM BibliogrLanguage GROUP BY BibliogrID, LanguageID, Authors, Source, Title);
DELETE FROM ConstSelLanguage WHERE ID NOT IN (SELECT MIN(ID) FROM ConstSelLanguage GROUP BY ConstSelID, LanguageID, Measure);
