use Crystal;
GO
sp_msforeachtable 'ALTER TABLE ? DISABLE TRIGGER all'
GO
ALTER TABLE dbo.Properties DROP CONSTRAINT DF_Properties_TableName;
GO
ALTER TABLE dbo.HeadTabl DROP CONSTRAINT DF_HeadTabl_Expert;
GO
ALTER TABLE dbo.HeadTabl DROP CONSTRAINT DF_HeadTabl_Help;
GO
ALTER TABLE dbo.HeadTabl DROP CONSTRAINT DF_HeadTabl_System;
GO
DROP INDEX IX_ElemTabl ON ElemTabl;
GO
ALTER TABLE dbo.AcOpTabl DROP CONSTRAINT U_AcOpTabl;
GO
ALTER TABLE dbo.ConstSel DROP CONSTRAINT U_ConstSel;
GO
ALTER TABLE dbo.CuryTabl DROP CONSTRAINT U_CuryTabl;
GO
ALTER TABLE dbo.DecrTabl DROP CONSTRAINT U_DecrTabl;
GO
ALTER TABLE dbo.DensTabl DROP CONSTRAINT U_DensTabl;
GO
ALTER TABLE dbo.DielDiss DROP CONSTRAINT U_DielDiss;
GO
ALTER TABLE dbo.Dielectr DROP CONSTRAINT U_Dielectr;
GO
ALTER TABLE dbo.Elastic1 DROP CONSTRAINT U_Elastic1;
GO
ALTER TABLE dbo.ElOpTabl DROP CONSTRAINT U_ElOpTabl;
GO
ALTER TABLE dbo.EsOpTabl DROP CONSTRAINT U_EsOpTabl;
GO
ALTER TABLE dbo.GrafTabl DROP CONSTRAINT U_GrafTabl;
GO
ALTER TABLE dbo.HardTabl DROP CONSTRAINT U_HardTabl;
GO
ALTER TABLE dbo.HeatExpn DROP CONSTRAINT U_HeatExpn;
GO
ALTER TABLE dbo.HeatTabl DROP CONSTRAINT U_HeatTabl;
GO
ALTER TABLE dbo.LitrTabl DROP CONSTRAINT U_LitrTabl;
GO
ALTER TABLE dbo.MechTabl DROP CONSTRAINT U_MechTabl;
GO
ALTER TABLE dbo.MnOpTabl DROP CONSTRAINT U_MnOpTabl;
GO
ALTER TABLE dbo.ModfTabl DROP CONSTRAINT U_ModfTabl;
GO
ALTER TABLE dbo.NlOpTabl DROP CONSTRAINT U_NlOpTabl;
GO
ALTER TABLE dbo.PlavTabl DROP CONSTRAINT U_PlavTabl;
GO
ALTER TABLE dbo.PzElTabl DROP CONSTRAINT U_PzElTabl;
GO
ALTER TABLE dbo.RefrcInd DROP CONSTRAINT U_RefrcInd;
GO
ALTER TABLE dbo.SistTabl DROP CONSTRAINT U_SistTabl;
GO
ALTER TABLE dbo.SuspTabl DROP CONSTRAINT U_SuspTabl;
GO
ALTER TABLE dbo.WavePure DROP CONSTRAINT U_WavePure;

use Crystal_en;
GO
sp_msforeachtable 'ALTER TABLE ? DISABLE TRIGGER all'
GO
ALTER TABLE dbo.Properties DROP CONSTRAINT DF_Properties_TableName;
GO
ALTER TABLE dbo.HeadTabl DROP CONSTRAINT DF_HeadTabl_Expert;
GO
ALTER TABLE dbo.HeadTabl DROP CONSTRAINT DF_HeadTabl_Help;
GO
ALTER TABLE dbo.HeadTabl DROP CONSTRAINT DF_HeadTabl_System;
GO
ALTER TABLE dbo.AcOpTabl DROP CONSTRAINT U_AcOpTabl;
GO
ALTER TABLE dbo.ConstSel DROP CONSTRAINT U_ConstSel;
GO
ALTER TABLE dbo.CuryTabl DROP CONSTRAINT U_CuryTabl;
GO
ALTER TABLE dbo.DecrTabl DROP CONSTRAINT U_DecrTabl;
GO
ALTER TABLE dbo.DensTabl DROP CONSTRAINT U_DensTabl;
GO
ALTER TABLE dbo.DielDiss DROP CONSTRAINT U_DielDiss;
GO
ALTER TABLE dbo.Dielectr DROP CONSTRAINT U_Dielectr;
GO
ALTER TABLE dbo.Elastic1 DROP CONSTRAINT U_Elastic1;
GO
ALTER TABLE dbo.ElemTabl DROP CONSTRAINT U_ElemTabl;
GO
ALTER TABLE dbo.ElOpTabl DROP CONSTRAINT U_ElOpTabl;
GO
ALTER TABLE dbo.EsOpTabl DROP CONSTRAINT U_EsOpTabl;
GO
ALTER TABLE dbo.GrafTabl DROP CONSTRAINT U_GrafTabl;
GO
ALTER TABLE dbo.HardTabl DROP CONSTRAINT U_HardTabl;
GO
ALTER TABLE dbo.HeatExpn DROP CONSTRAINT U_HeatExpn;
GO
ALTER TABLE dbo.HeatTabl DROP CONSTRAINT U_HeatTabl;
GO
ALTER TABLE dbo.LitrTabl DROP CONSTRAINT U_LitrTabl;
GO
ALTER TABLE dbo.MechTabl DROP CONSTRAINT U_MechTabl;
GO
ALTER TABLE dbo.MnOpTabl DROP CONSTRAINT U_MnOpTabl;
GO
ALTER TABLE dbo.ModfTabl DROP CONSTRAINT U_ModfTabl;
GO
ALTER TABLE dbo.NlOpTabl DROP CONSTRAINT U_NlOpTabl;
GO
ALTER TABLE dbo.PlavTabl DROP CONSTRAINT U_PlavTabl;
GO
ALTER TABLE dbo.PzElTabl DROP CONSTRAINT U_PzElTabl;
GO
ALTER TABLE dbo.RefrcInd DROP CONSTRAINT U_RefrcInd;
GO
ALTER TABLE dbo.SistTabl DROP CONSTRAINT U_SistTabl;
GO
ALTER TABLE dbo.SuspTabl DROP CONSTRAINT U_SuspTabl;
GO
ALTER TABLE dbo.WavePure DROP CONSTRAINT U_WavePure;

use Crystal;
GO
CREATE TABLE dbo.Languages (
    ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    Name VARCHAR(2)
);
INSERT INTO dbo.Languages
(Name)
VALUES
('ru'),  ('en');
GO
ALTER TABLE dbo.AcOpTabl ADD LanguageID int NOT NULL CONSTRAINT DF_AcOpTabl_LanguageID DEFAULT(1);
ALTER TABLE dbo.Bibliogr ADD LanguageID int NOT NULL CONSTRAINT DF_Bibliogr_LanguageID DEFAULT(1);
ALTER TABLE dbo.ConstSel ADD LanguageID int NOT NULL CONSTRAINT DF_ConstSel_LanguageID DEFAULT(1);
ALTER TABLE dbo.CuryTabl ADD LanguageID int NOT NULL CONSTRAINT DF_CuryTabl_LanguageID DEFAULT(1);
ALTER TABLE dbo.DecrTabl ADD LanguageID int NOT NULL CONSTRAINT DF_DecrTabl_LanguageID DEFAULT(1);
ALTER TABLE dbo.DensTabl ADD LanguageID int NOT NULL CONSTRAINT DF_DensTabl_LanguageID DEFAULT(1);
ALTER TABLE dbo.DielDiss ADD LanguageID int NOT NULL CONSTRAINT DF_DielDiss_LanguageID DEFAULT(1);
ALTER TABLE dbo.Dielectr ADD LanguageID int NOT NULL CONSTRAINT DF_Dielectr_LanguageID DEFAULT(1);
ALTER TABLE dbo.Elastic1 ADD LanguageID int NOT NULL CONSTRAINT DF_Elastic1_LanguageID DEFAULT(1);
ALTER TABLE dbo.ElemTabl ADD LanguageID int NOT NULL CONSTRAINT DF_ElemTabl_LanguageID DEFAULT(1);
ALTER TABLE dbo.ElemTablNew ADD LanguageID int NOT NULL CONSTRAINT DF_ElemTablNew_LanguageID DEFAULT(1);
ALTER TABLE dbo.ElOpTabl ADD LanguageID int NOT NULL CONSTRAINT DF_ElOpTabl_LanguageID DEFAULT(1);
ALTER TABLE dbo.EsOpTabl ADD LanguageID int NOT NULL CONSTRAINT DF_EsOpTabl_LanguageID DEFAULT(1);
ALTER TABLE dbo.GrafTabl ADD LanguageID int NOT NULL CONSTRAINT DF_GrafTabl_LanguageID DEFAULT(1);
ALTER TABLE dbo.HardTabl ADD LanguageID int NOT NULL CONSTRAINT DF_HardTabl_LanguageID DEFAULT(1);
ALTER TABLE dbo.HeadTabl ADD LanguageID int NOT NULL CONSTRAINT DF_HeadTabl_LanguageID DEFAULT(1);
ALTER TABLE dbo.HeatExpn ADD LanguageID int NOT NULL CONSTRAINT DF_HeatExpn_LanguageID DEFAULT(1);
ALTER TABLE dbo.HeatTabl ADD LanguageID int NOT NULL CONSTRAINT DF_HeatTabl_LanguageID DEFAULT(1);
ALTER TABLE dbo.LastModified ADD LanguageID int NOT NULL CONSTRAINT DF_LastModified_LanguageID DEFAULT(1);
ALTER TABLE dbo.MechTabl ADD LanguageID int NOT NULL CONSTRAINT DF_MechTabl_LanguageID DEFAULT(1);
ALTER TABLE dbo.MnOpTabl ADD LanguageID int NOT NULL CONSTRAINT DF_MnOpTabl_LanguageID DEFAULT(1);
ALTER TABLE dbo.ModfTabl ADD LanguageID int NOT NULL CONSTRAINT DF_ModfTabl_LanguageID DEFAULT(1);
ALTER TABLE dbo.NlOpTabl ADD LanguageID int NOT NULL CONSTRAINT DF_NlOpTabl_LanguageID DEFAULT(1);
ALTER TABLE dbo.PlavTabl ADD LanguageID int NOT NULL CONSTRAINT DF_PlavTabl_LanguageID DEFAULT(1);
ALTER TABLE dbo.Properties ADD LanguageID int NOT NULL CONSTRAINT DF_Properties_LanguageID DEFAULT(1);
ALTER TABLE dbo.PzElTabl ADD LanguageID int NOT NULL CONSTRAINT DF_PzElTabl_LanguageID DEFAULT(1);
ALTER TABLE dbo.RefrcInd ADD LanguageID int NOT NULL CONSTRAINT DF_RefrcInd_LanguageID DEFAULT(1);
ALTER TABLE dbo.SuspTabl ADD LanguageID int NOT NULL CONSTRAINT DF_SuspTabl_LanguageID DEFAULT(1);
ALTER TABLE dbo.RefrTabl ADD LanguageID int NOT NULL CONSTRAINT DF_RefrTabl_LanguageID DEFAULT(1);

use Crystal_en;
GO
CREATE TABLE dbo.Languages (
    ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    Name VARCHAR(2)
);
INSERT INTO dbo.Languages
(Name)
VALUES
('ru'),  ('en');
GO
ALTER TABLE dbo.AcOpTabl ADD LanguageID int NOT NULL CONSTRAINT DF_AcOpTabl_LanguageID DEFAULT(2);
ALTER TABLE dbo.Bibliogr ADD LanguageID int NOT NULL CONSTRAINT DF_Bibliogr_LanguageID DEFAULT(2);
ALTER TABLE dbo.ConstSel ADD LanguageID int NOT NULL CONSTRAINT DF_ConstSel_LanguageID DEFAULT(2);
ALTER TABLE dbo.CuryTabl ADD LanguageID int NOT NULL CONSTRAINT DF_CuryTabl_LanguageID DEFAULT(2);
ALTER TABLE dbo.DecrTabl ADD LanguageID int NOT NULL CONSTRAINT DF_DecrTabl_LanguageID DEFAULT(2);
ALTER TABLE dbo.DensTabl ADD LanguageID int NOT NULL CONSTRAINT DF_DensTabl_LanguageID DEFAULT(2);
ALTER TABLE dbo.DielDiss ADD LanguageID int NOT NULL CONSTRAINT DF_DielDiss_LanguageID DEFAULT(2);
ALTER TABLE dbo.Dielectr ADD LanguageID int NOT NULL CONSTRAINT DF_Dielectr_LanguageID DEFAULT(2);
ALTER TABLE dbo.Elastic1 ADD LanguageID int NOT NULL CONSTRAINT DF_Elastic1_LanguageID DEFAULT(2);
ALTER TABLE dbo.ElemTabl ADD LanguageID int NOT NULL CONSTRAINT DF_ElemTabl_LanguageID DEFAULT(2);
ALTER TABLE dbo.ElemTablNew ADD LanguageID int NOT NULL CONSTRAINT DF_ElemTablNew_LanguageID DEFAULT(2);
ALTER TABLE dbo.ElOpTabl ADD LanguageID int NOT NULL CONSTRAINT DF_ElOpTabl_LanguageID DEFAULT(2);
ALTER TABLE dbo.EsOpTabl ADD LanguageID int NOT NULL CONSTRAINT DF_EsOpTabl_LanguageID DEFAULT(2);
ALTER TABLE dbo.GrafTabl ADD LanguageID int NOT NULL CONSTRAINT DF_GrafTabl_LanguageID DEFAULT(2);
ALTER TABLE dbo.HardTabl ADD LanguageID int NOT NULL CONSTRAINT DF_HardTabl_LanguageID DEFAULT(2);
ALTER TABLE dbo.HeadTabl ADD LanguageID int NOT NULL CONSTRAINT DF_HeadTabl_LanguageID DEFAULT(2);
ALTER TABLE dbo.HeatExpn ADD LanguageID int NOT NULL CONSTRAINT DF_HeatExpn_LanguageID DEFAULT(2);
ALTER TABLE dbo.HeatTabl ADD LanguageID int NOT NULL CONSTRAINT DF_HeatTabl_LanguageID DEFAULT(2);
ALTER TABLE dbo.LastModified ADD LanguageID int NOT NULL CONSTRAINT DF_LastModified_LanguageID DEFAULT(2);
ALTER TABLE dbo.MechTabl ADD LanguageID int NOT NULL CONSTRAINT DF_MechTabl_LanguageID DEFAULT(2);
ALTER TABLE dbo.MnOpTabl ADD LanguageID int NOT NULL CONSTRAINT DF_MnOpTabl_LanguageID DEFAULT(2);
ALTER TABLE dbo.ModfTabl ADD LanguageID int NOT NULL CONSTRAINT DF_ModfTabl_LanguageID DEFAULT(2);
ALTER TABLE dbo.NlOpTabl ADD LanguageID int NOT NULL CONSTRAINT DF_NlOpTabl_LanguageID DEFAULT(2);
ALTER TABLE dbo.PlavTabl ADD LanguageID int NOT NULL CONSTRAINT DF_PlavTabl_LanguageID DEFAULT(2);
ALTER TABLE dbo.Properties ADD LanguageID int NOT NULL CONSTRAINT DF_Properties_LanguageID DEFAULT(2);
ALTER TABLE dbo.PzElTabl ADD LanguageID int NOT NULL CONSTRAINT DF_PzElTabl_LanguageID DEFAULT(2);
ALTER TABLE dbo.RefrcInd ADD LanguageID int NOT NULL CONSTRAINT DF_RefrcInd_LanguageID DEFAULT(2);
ALTER TABLE dbo.SuspTabl ADD LanguageID int NOT NULL CONSTRAINT DF_SuspTabl_LanguageID DEFAULT(2);
ALTER TABLE dbo.RefrTabl ADD LanguageID int NOT NULL CONSTRAINT DF_RefrTabl_LanguageID DEFAULT(2);
